name: Check backend (single job)

on:
  pull_request:

  backend_single_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            php:
              - **/*.php
            phpunit:
              - **/*.php
              - phpunit.xml.dist
            any:
              - *phpunit

      - name: Composer
        if: ${{ steps.filter.outputs.php == 'true' }}
        run: echo "Running Composer if anything backend-related changed"

      - name: PHPUnit
        if: ${{ steps.filter.outputs.phpunit == 'true' }}
        run: echo "Running PHPUnit"
