name: Check backend (single job)

on:
  pull_request:

jobs:
  backend_single_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            php: &php
              - "**/*.php"
            workflow: &workflow
              - .github/workflows/check-backend-single-job.yml
            phpcs: &phpcs
                - *php
                - phpcs.xml.dist
            phpunit: &phpunit
              - *php
              - phpunit.xml.dist
            any:
              - *phpunit
              - *workflow

      - name: Composer
        if: ${{ steps.filter.outputs.any == 'true' }}
        run: echo "Running Composer if anything backend-related changed"

      - uses: dorny/paths-filter@v3
        id: filter-changed-php-files
        if: ${{ steps.filter.outputs.phpcs == 'true' }}
        with:
          list-files: shell
          filters: |
            phpcs:
              - '**/*.php'
              - 'phpcs.xml.dist'

      - name: PHP CodeSniffer on changed files
        if: ${{ steps.filter.outputs.phpcs == 'true' }}
        run: |
          files="${{ steps.filter-changed-php-files.outputs.phpcs_files }}"
          if [ -n "$files" ]; then
            echo "Running phpcs on changed files:"
            echo "$files"
            vendor/bin/phpcs $files
          else
            echo "No PHP files changed, skipping phpcs."
          fi

      - name: PHPUnit
        if: ${{ steps.filter.outputs.phpunit == 'true' }}
        run: echo "Running PHPUnit"
