name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - LATEST
      - STAGING
concurrency:
  group: ${{ github.workflow }}

env:
  RELEASES_PATH: "~/arueckauer-deploy-workflow/"

jobs:
  setup:
    environment: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' ? 'testing' : github.event_name == 'push' && github.ref == 'refs/tags/STAGING' ? 'staging' : github.event_name == 'push' && github.ref == 'refs/tags/LATEST' ? 'production' : 'unknown' } }
    runs-on: ubuntu-latest
    steps:

      - name: Show environment
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SCP_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCP_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }} "echo 'SSH connection successful'" || exit 1

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to Testing
        run: scp index.md ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }}:${{ env.RELEASES_PATH }}${{ vars.ENVIRONMENT }}
