name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - LATEST
      - STAGING
concurrency:
  group: ${{ github.workflow }}

env:
  RELEASES_PATH: "~/arueckauer-deploy-workflow/"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Set Environment
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=testing" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/LATEST" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/STAGING" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          else
            echo "Unsupported event or branch/tag"
            exit 1
          fi

      - name: Show environment
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SCP_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCP_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }} "echo 'SSH connection successful'" || exit 1

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to Testing
        run: scp index.md ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }}:${{ env.RELEASES_PATH }}${{ vars.ENVIRONMENT }}
