name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - LATEST
      - STAGING
concurrency:
  group: ${{ github.ref }}

env:
  RELEASES_PATH: "~/arueckauer-deploy-workflow/"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
        environment: ${{ env.ENVIRONMENT }}
    steps:

      - name: Set Environment
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=testing" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/STAGING" ]]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/LATEST" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "Unsupported event or branch/tag"
            exit 1
          fi

  checkout:
    name: Checkout code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export repository
        run: |
          tar -czf repository.tar.gz -C . .
          echo "::set-output name=repository::repository.tar.gz"
        id: repository

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:

      - name: Import repository
        run: |
          tar -xzf ${{ needs.checkout.outputs.repository }}
        id: repository

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: index.md
          path: index.md

  deploy:
    needs: [setup, build]
    environment: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:

      - name: Show environment
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "vars.UNIQUE_ID: ${{ vars.UNIQUE_ID }}"
          echo "vars.ENVIRONMENT: ${{ vars.ENVIRONMENT }}"
          echo "env.ENVIRONMENT: ${{ env.ENVIRONMENT }}"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: index.md
          path: .

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SCP_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCP_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }} "echo 'SSH connection successful'" || exit 1
          echo "known hosts:"
          cat ~/.ssh/known_hosts

      - name: Deploy
        run: scp index.md ${{ secrets.SCP_USERNAME }}@${{ secrets.SCP_HOST }}:${{ env.RELEASES_PATH }}${{ vars.ENVIRONMENT }}
