name: Update PHP Dependencies

on:
  schedule:
    - cron: '30 6 * * 4' # Each Thursday at 06:30
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: GitHub Actions
      GIT_AUTHOR_EMAIL: actions@github.com
      GIT_COMMITTER_NAME: GitHub Actions
      GIT_COMMITTER_EMAIL: actions@github.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          ini-values: date.timezone=Europe/Zurich

      - name: Update dependencies in main app
        run: |
          composer u -W
          composer bump
          composer u --lock
        working-directory: .

      - name: Generate main app diff
        id: main_diff
        run: |
          git diff composer.json > main.diff
          php .github/workflows/diff-2-commit-message-entry.php main.diff > main.changelog

      - name: Commit main app changes
        run: |
          if git diff --quiet composer.json composer.lock; then
            echo "No changes in main app"
          else
            git add composer.json composer.lock
            git commit -m "$(cat .github/workflows/commit-message-template.txt; cat main.changelog)"
          fi

      - name: Push changes
        run: |
          git push origin HEAD:update-deps-$(date +'%Y%m%d')

      - name: Clean up temp files
        run: |
          rm -f main.changelog main.diff
          rm -rf vendor

      - name: Set DATE env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-deps-${{ env.DATE }}
          title: "Chore: PHP dependencies update (${{ env.DATE }})"
          body: '## Description

Update dependencies to latest stable versions

This commit updates the project dependencies to their latest stable versions where possible without a major update. The update includes both production and development dependencies to ensure compatibility, security, and access to the latest features.'
          reviewers: arueckauer
          labels: dependencies
